CREATE TABLE "ORACLEUSR"."INFOMATION" 
("BIKENUMBER" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"ADRESS" VARCHAR2(255 BYTE), 
	"ID" VARCHAR2(20 BYTE) , PRIMARY KEY (ID)
);
CREATE SEQUENCE INFOMATION_SEQ
 START WITH 100
 INCREMENT BY 1;